### ISSUE TITLE
UE Crash in new Experimental Build

### ISSUE THREAD

**Issue by gwilku** [Panakotta00/LightItUp#11]
Today a new update was rolled out: Patch Notes: Early Access (EXPERIMENTAL) - v0.3.4.11 - Build 122801, and after the patch the game doesn't launch with LightItUp 0.5.4.
I guess that this pre-launch-debug part might be helpful:

Resolved imports successfully; Calling DllMain
Called DllMain successfully on DLL. Loading finished.
Successfully loaded module "UE4-SML-Win64-Shipping.dll"
Bootstrapping loader modules...
Bootstrapping module UE4-SML-Win64-Shipping.dll
Loaded Raw DLL module: MZ
Casted module to dos header 00007FF83DFC0000
Magic: 23117 Expected Magic: 23117
Import Directory Size: 200
Removing protection from page 00007FF83DFD71F4
Removing protection from page 00007FF83DFCDD40
[FATAL] Executable missing symbol with mangled name: ?ShouldBeConsideredForBase_Implementation@AFGBuildableFactory@@UEAA_NXZ
[FATAL] De-mangled symbol name (for reference): public: virtual bool __cdecl AFGBuildableFactory::ShouldBeConsideredForBase_Implementation(void) __ptr64
[FATAL] Overriding it with dummy symbol. Bad things will happen if it is going to be actually called!
Removing protection from page 00007FF83DFCE000
Resolved imports successfully; Calling DllMain
Called DllMain successfully on DLL. Loading finished.
Successfully performed bootstrapping.

**Comment by rpg500e** [comment]
> Today a new update was rolled out: Patch Notes: Early Access (EXPERIMENTAL) - v0.3.4.11 - Build 122801, and after the patch the game doesn't launch with LightItUp 0.5.4.
> I guess that this pre-launch-debug part might be helpful:
> 
> Resolved imports successfully; Calling DllMain
> Called DllMain successfully on DLL. Loading finished.
> Successfully loaded module "UE4-SML-Win64-Shipping.dll"
> Bootstrapping loader modules...
> Bootstrapping module UE4-SML-Win64-Shipping.dll
> Loaded Raw DLL module: MZ�
> Casted module to dos header 00007FF83DFC0000
> Magic: 23117 Expected Magic: 23117
> Import Directory Size: 200
> Removing protection from page 00007FF83DFD71F4
> Removing protection from page 00007FF83DFCDD40
> [FATAL] Executable missing symbol with mangled name: ?ShouldBeConsideredForBase_Implementation@AFGBuildableFactory@@UEAA_NXZ
> [FATAL] De-mangled symbol name (for reference): public: virtual bool __cdecl AFGBuildableFactory::ShouldBeConsideredForBase_Implementation(void) __ptr64
> [FATAL] Overriding it with dummy symbol. Bad things will happen if it is going to be actually called!
> Removing protection from page 00007FF83DFCE000
> Resolved imports successfully; Calling DllMain
> Called DllMain successfully on DLL. Loading finished.
> Successfully performed bootstrapping.

Same, what're you doing meanwhile? I'm just finding out mods don't show up in the online map editor...

**Comment by gwilku** [comment]
Meanwhile? I started another session without the broken mods (it's this one and Refined Power 2.0.5. has similar issue as well). Seems both of them refer to something that has been renamed or removed in the latest patch.

Also: none of the mods I use show on the map (satisfactory-calculator), if this is what you mean.

**Comment by dragofier** [comment]
Hopefully this will be helpful.

Version: 122801, IsPerforceBuild: false, BuildConfiguration: Shipping, Launcher: Epic NetMode: -

Assertion failed: ObjectA == nullptr || ObjectA->IsA<UClass>() [File:D:\ws\SB-160502110050-fad\UE4\Engine\Source\Runtime\CoreUObject\Private\UObject\PropertyClass.cpp] [Line: 156]

FactoryGame_Win64_Shipping!FWindowsErrorOutputDevice::Serialize() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\core\private\windows\windowserroroutputdevice.cpp:79]
FactoryGame_Win64_Shipping!FOutputDevice::LogfImpl() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\core\private\misc\outputdevice.cpp:71]
FactoryGame_Win64_Shipping!AssertFailedImplV() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\core\private\misc\assertionmacros.cpp:101]
FactoryGame_Win64_Shipping!FDebug::CheckVerifyFailedImpl() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\core\private\misc\assertionmacros.cpp:439]
FactoryGame_Win64_Shipping!UClassProperty::Identical() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\coreuobject\private\uobject\propertyclass.cpp:156]
FactoryGame_Win64_Shipping!UBlueprintGeneratedClass::BuildCustomPropertyListForPostConstruction() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\blueprintgeneratedclass.cpp:470]
FactoryGame_Win64_Shipping!UBlueprintGeneratedClass::UpdateCustomPropertyListForPostConstruction() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\blueprintgeneratedclass.cpp:608]
FactoryGame_Win64_Shipping!UBlueprintGeneratedClass::SerializeDefaultObject() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\engine\private\blueprintgeneratedclass.cpp:319]
FactoryGame_Win64_Shipping!FAsyncPackage::EventDrivenSerializeExport() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\coreuobject\private\serialization\asyncloading.cpp:3610]
FactoryGame_Win64_Shipping!FAsyncPackage::ProcessImportsAndExports_Event() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\coreuobject\private\serialization\asyncloading.cpp:3937]
FactoryGame_Win64_Shipping!<lambda_34eee40e849fa2534d7a680d55b737bd>::operator()() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\coreuobject\private\serialization\asyncloading.cpp:2736]
FactoryGame_Win64_Shipping!FAsyncLoadingThread::ProcessAsyncLoading() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\coreuobject\private\serialization\asyncloading.cpp:4488]
FactoryGame_Win64_Shipping!FAsyncLoadingThread::TickAsyncThread() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\coreuobject\private\serialization\asyncloading.cpp:5269]
FactoryGame_Win64_Shipping!FAsyncLoadingThread::Run() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\coreuobject\private\serialization\asyncloading.cpp:5196]
FactoryGame_Win64_Shipping!FRunnableThreadWin::Run() [d:\ws\sb-160502110050-fad\ue4\engine\source\runtime\core\private\windows\windowsrunnablethread.cpp:96]

**Comment by dragofier** [comment]
I walked through the mods I use and only Light it up was affected.  The above is what was dumped to screen when this mod  is by itself.
I have SML: 2.1.2

**Comment by Panakotta00** [comment]
The latests updates should have solved it.
