### ISSUE TITLE
All lights are flickering in EA after Update 3.4.15

### ISSUE THREAD

**Issue by staratnight** [Panakotta00/LightItUp#12]
SML: 2.1.2
LightItUp: 0.5.6

After Updating Early Access version to 3.4.14 all lights on my map were flickering. 
It does not matter whether the lamps were turned off or on and if turned on in what mode they were.
In mode _Auto_ it also does not matter what daytime it is.

What I tried to fix the issue on my own:
- Turning Lamp off and on again
- Removing and reconnecting power to the lamp
- Disassembling and rebuilding lamp
- Uninstalling Mod - started without Mod - reinstalling Mod

Seems to affect at least 
- Lamp Pole
- Street Lamp
- Powerpole Lamp
- Wall and Ceiling Lamps

For now I disconnected all my lamps from power so I reduced disco-related headache ;)
P.S.: Thanks for this awesome mod. Keep up the great work!

**Comment by staratnight** [comment]
Flickering still seen after updating to 3.4.15

**Comment by kwstoudt** [comment]
Also seen on 3.4.16 with all lamps that are electrically powered. (Fuel-powered lamps work fine)

**Comment by staratnight** [comment]
After updating Satsfactory to 3.5.1 and Light It Up to 0.5.7 the flickering is gone! 

Thank you guys and keep up the good work!
