### ISSUE TITLE
CL134641 SML v2.2.1

### ISSUE THREAD

**Issue by Totomio** [Panakotta00/LightItUp#14]
Mod broken with the last update (CL134641), you can buy, place items, but while you try to powered them the game crash with no errors. 

- No other mods installed.
- Fuels Lamps not affected by the issue.

Edit 30.10.2020 - Problem solved with the maj (0.5.10) - Thanks ;-)

**Comment by DerekWearmouth** [comment]
Elaborate for a newer player with this issue please @Totomio 

Problem solved with the maj (0.5.10) - Thanks ;-)

**Comment by DerekWearmouth** [comment]
V0.5.10 did not fix the issue.

**Comment by Totomio** [comment]
In the Early Access branch you have to use the 0.5.8 version of the mod to make it work. The v0.5.10 fix the light for the Experimental only.

**Comment by Totomio** [comment]
In the Early Access branch you have to use the 0.5.8 version of the mod to make it work. The v0.5.10 fix the light for the Experimental version of the game.

**Comment by esteinborn** [comment]
Rolling back to 0.5.8 resolved the issue for me. thanks for the answer
