### ISSUE TITLE
Placing lamp pole freezes and then crashes game

### ISSUE THREAD

**Issue by ReikaKalseki** [Panakotta00/LightItUp#15]
This lamp pole, specifically: ![https://i.imgur.com/rmDDW5z.jpg](https://i.imgur.com/rmDDW5z.jpg).

This only seems to happen on the newest version; the 5.8 version works fine.

I am using the latest non-experimental version of the game.

**Comment by esteinborn** [comment]
See #14 0.5.9-0.5.10 are only meant for experimental branch at the moment.

You can roll back your version in the dropdown in the SMM app. Next time it tells you it has an update for lightitup, click ignore.
