### ISSUE TITLE
Crashing when trying to join a multiplayer session or Crashing when try to set up Lamp settings in Multiplayer (clientside)

### ISSUE THREAD

**Issue by Cebraxo** [Panakotta00/LightItUp#2]
Soo when you Delete the DLL file You are able to join a session with a friend that has the DLL and the .sig and .pak files installed. So yea, if the client tries setting up the lamp it crashed them. And the light doesnt render on multiplayer. Please try to fix it!

**Comment by sveini4u** [comment]
Pleaseeeeee Fix this mod to Multiplayer!!! I need this mod!!! I can pay you!!!!now!!! To fix itt

**Comment by Panakotta00** [comment]
Multiplayer support probably will come with SML 2.0 but I cant ensure to implement it first SML 2.0 version realease.

Sry for the late response ^^

**Comment by Panakotta00** [comment]
Multiplayer support is now released and you should be able to enjoy it with your friends.
