### ISSUE TITLE
compatibility issues | other mods

### ISSUE THREAD

**Issue by hexpr** [Panakotta00/LightItUp#6]
compatibility issues with mods that add new items

**Comment by Panakotta00** [comment]
Can you tell me more, cause I don't understand exactly what Issue you're facing

**Comment by vinnyviking** [comment]
Maybe this helps solving this issue

I do have an issue that after researching the licht in tier 1 I do not get the menu and/or objects to build (i.e. no lamps)

I run build 118201 Early Access
I have the following mods installed
Storeage teleporter
Programmable elevator
Renewed power
farming mod (not tested yet)
Light up
upside Down Foundation
10+ inventory slots
Advanced splitter
PermaDay (not working)
Advanced logistics
Passive mode

Most of these mods work as expected.
