### ISSUE TITLE
Portable Lamp Cannot be Disassembled/Removed from the World!

### ISSUE THREAD

**Issue by chloeprince** [Panakotta00/LightItUp#9]
Mod version of Lightitup 0.5.4
Running Experimental 120461
SML 2.1.0

I placed a Portable Lamp in the world, and now it can't be disassembled/removed from the world!

I really don't want to have to remove the mod just to get rid of it because I placed other lights in the world and would have to go back and put them all back in.

**Comment by Panakotta00** [comment]
You can remove it by clicking the "Pick Up" button in the interaction UI.

**Comment by CovertJaguar** [comment]
I just want to comment that a white button on a white background is really hard to see!
